name: test from other repo
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        type: string
        default: 14.x
        
      yarn-test:
        description: 'Run Yarn test ?'
        required: false
        default: 'no'
        type: string

      eslint:
        description: 'Run ESLint ?'
        required: false
        default: 'no'
        type: string
      
        

  pull_request:
    branches:
      - main
    types:
      - opened


permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:


  test-manual:
    name: Yarn test manual
    if: github.event_name =='workflow_dispatch'
    uses: loiluong-kobiton/myTesting-CICD/.github/workflows/manual.yml@sub-main-3
    with:
      yarn-test: ${{ inputs.yarn-test }}
      eslint: ${{ inputs.eslint }}
  
  
  test-auto:
    name: Yarn test auto
    # if: github.event_name != 'pull_request' && github.event.pull_request.merged == false
    if: github.event_name != 'pull_request'
    uses: loiluong-kobiton/myTesting-CICD/.github/workflows/manual.yml@sub-main-3
    with:
      yarn-test: 'yes'
      eslint: 'yes'

  # build-doc:
  #   name: Build API Doc V1
  #   uses: kobiton/deployment/.github/workflows/ci-api-doc.yaml@master
  #   with:
  #     git-ref: ${{ github.event.inputs.git-ref }}
  #     repo-name: api-doc-v1
  #   secrets: inherit