name: test from other repo
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        type: string
        default: 14.x
      yarn-test:
        description: 'Run Yarn test ?'
        required: false
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
      eslint:
        description: 'Run ESLint ?'
        required: false
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
  
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened


jobs:
  # greet:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send greeting
  #       run: echo "Hello this is testing install and test Node.js ${{ github.event.inputs.node-version }}"

  test:
    name: Yarn test
    uses: loiluong-kobiton/myTesting-CICD/.github/workflows/manual.yml@sub-main-3
    with:
      yarn-test: 'true'
      eslint: 'true'

  # build-doc:
  #   name: Build API Doc V1
  #   uses: kobiton/deployment/.github/workflows/ci-api-doc.yaml@master
  #   with:
  #     git-ref: ${{ github.event.inputs.git-ref }}
  #     repo-name: api-doc-v1
  #   secrets: inherit