name: test from other repo
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        type: string
        default: 14.x
        
      yarn-test:
        description: 'Run Yarn test ?'
        required: false
        default: 'no'
        type: string

      eslint:
        description: 'Run ESLint ?'
        required: false
        default: 'no'
        type: string
      
        
  push:
    branches:
      - main

  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened

  pull_request_target:
    branches:
      - main


permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  # greet:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send greeting
  #       run: echo "Hello this is testing install and test Node.js ${{ github.event.inputs.node-version }}"

  test-manual:
    name: Yarn test manual
    if: github.event_name =='workflow_dispatch'
    uses: loiluong-kobiton/myTesting-CICD/.github/workflows/manual.yml@sub-main-3
    with:
      yarn-test: ${{ inputs.yarn-test }}
      eslint: ${{ inputs.eslint }}
  
  
  test-auto:
    name: Yarn test auto
    if: github.event_name != 'workflow_dispatch'
    uses: loiluong-kobiton/myTesting-CICD/.github/workflows/manual.yml@sub-main-3
    with:
      yarn-test: 'yes'
      eslint: 'yes'

